<head>
  <link rel="preload" href="/videos/video1.mp4" as="video" type="video/mp4" />
  <link rel="preload" href="/videos/video2.mp4" as="video" type="video/mp4" />
  <link rel="preload" href="/videos/video3.mp4" as="video" type="video/mp4" />
  <link rel="preload" href="/videos/video4.mp4" as="video" type="video/mp4" />
</head>


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
